version: 0.2

phases:
  build:
    commands:
      - echo "Packaging LF1 and LF2 as separate artifacts..."

artifacts:
  secondary-artifacts:
    LF1Artifact:
      base-directory: lambda-functions/LF1
      files:
        - '**/*'
    LF2Artifact:
      base-directory: lambda-functions/LF2
      files:
        - '**/*'